services:
  - type: web
    name: gdsmapix
    runtime: static
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
